import "./globals.css";
import { Montserrat } from "next/font/google";
import Nav from "@/components/Nav";
import Header from "@/components/Header";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  min-h-screen bg-light bg-cover bg-no-repeat relative mx-10`}
      >
        <Nav />
        <Header />
        {children}
      </body>
    </html>
  );
}
